image_root:
  all: '/workspace1/fidelrio/flickr30k/imgs/'
  train_gender: '/workspace1/fidelrio/sd_gender_images/image_0_'
image_exts:
  all: '.jpg'
  train_gender: '.png'
ann_root: '/mnt/nas2/GrimaRepo/fidelrio/generative-data-augmentation/'
dataset: 'caption_augmented_flickr'
list_skills: 'gender'
available_skills: 'gender,color'

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth'
pretrained: '/mnt/nas2/GrimaRepo/fidelrio/BLIP/checkpoints/model_base.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
# batch_size: 32
batch_size: 24
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 50

patience: 5
early_stopping_metric: bleu4
